config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root to: 'dashboards#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def create
    user_email = User.where("email = ?", params[:user][:email]).first
    if user_email
      if user_email
        user = warden.authenticate!(auth_options)
        if user
          if session["url"]
            redirect_to session["url"]
          else
            redirect_to root_path
          end
        else
          flash[:error] = "Email or Password invalid"
          render 'new'
        end
      else
        warden.logout
        flash[:notice] = "You didn't have more access"
        redirect_to new_user_session_path
      end
    else
      warden.logout
      render json: {status: 402, messages: "Sorry, You didn't have more access"}
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    sign_out(@user)
    @current_user = nil
    redirect_to new_user_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<body>
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <section class="hero is-info welcome is-small">
          <div class="hero-body">
            <div class="container">
              <h1 class="title">
                  Hello, <#%= current_user.name%>.
              </h1>
              <h2 class="subtitle">
                  I hope you are having a great day!
              </h2>
                      <div class="level-left">
                  <%= form_tag root_path, method: :get do %>
                    <div class="level-item">
                      <div class="control">
                        <% from_date = params[:from_date].present? ? params[:from_date] : Date.current.strftime('%Y-%m-%d') %>
                                <% end_date = params[:end_date].present? ? params[:end_date] : Date.current.strftime('%Y-%m-%d') %>
                        <b><label> From Date : </label></b>
                                <input type="date" class="control datepicker" placeholder="From Date..." name="from_date" value="<%= from_date %>">
                        <b><label> To Date : </label></b>
                                <input type="date" class="control datepicker" id="end_date" placeholder="To Date..." name="end_date" value="<%= end_date %>">
                        </div>
                        <div class="level-item">
                          <%= submit_tag "Filter", class: "button" %>
                        </div>
                      </div>  
                  <% end %>
                </div>
            </div>
          </div>
        </section>
        <br>
        <section class="info-tiles">
          <div class="tile is-ancestor has-text-centered">
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title"><%#= @total_users%></p>
                <p class="subtitle">Users</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title"><%#= @total_store %></p>
                <p class="subtitle">Stores</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title"><%#= @total_product %></p>
                <p class="subtitle">Products</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title"><%#= @total_tr %></p>
                <p class="subtitle">Transactions</p>
              </article>
            </div>
           <div class="tile is-parent">
              <article class="tile is-child box" style="width: 440px;">
                <p class="subtitle"><b><%#= number_to_currency(@total_trdetail, unit: "Rp.", separator: ",", delimiter: ".") %></b></p>
                <p class="subtitle">Total Transactions</p>
              </article>
            </div>
          </div>
        </section>
        <div class="columns">
          <div class="column is-12">
            <div class="card events-card">
              <header class="card-header">
                <p class="card-header-title">
                  Top Ups
                </p>
                <a href="#" class="card-header-icon" aria-label="more options">
                  <span class="icon">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                  </span>
                </a>
              </header>
              <div class="card-table">
                <div class="content">
                  <table class="table is-fullwidth is-striped">
                    <thead> 
                      <tr>
                        <th>User Name</th>
                        <th>Top Up Balance</th>
                        <th>Bank Name</th>
                        <th>Status</th>
                        <th>Created At</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                    </tbody>
                  </table>
                </div>
              </div>
              <footer class="card-footer">
                
              </footer>
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<%if user_signed_in? %>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CRM Dashboard</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <link rel="stylesheet" href="/assets/dasboard.css">
  <link rel="javascript" href="/assets/application.js">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+HK:100,300,400,500,700,900&display=swap" rel="stylesheet">

  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag Ckeditor.cdn_url %>
  <%= csrf_meta_tags %>

  <%#= favicon_link_tag asset_path('animo_tab.jpg') %>
</head>

<body>

  <%= render partial: 'layouts/navigations/public.html.erb'%>
  <div id="main">
    <div class="wrapper">
      <%= render partial: 'layouts/navigations/sidebar'%>
      
      <% if notice %>
      <p class="help is-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="help is-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </div>
  <%= render partial: 'layouts/navigations/footer.html.erb'%>
  <!---------------------------------------------------------------------------------------->

  <!-- All of BulmaJS -->
  <script src="../BulmaJS-0.10.0/BulmaJS-0.10.0/dist/bulma.js"></script>
  <script async type="text/javascript" src="../js/bulma.js"></script>
  <!-- Single plugins -->
  <script src="../BulmaJS-0.10.0/BulmaJS-0.10.0/dist/navbar.js"></script>
<!--  <script src="jquery-3.3.1.min.js"></script>-->
  <script src="mainjs.js"></script>

  <script>
    (function() {
      var burger = document.querySelector('.burger');
      var nav = document.querySelector('#' + burger.dataset.target);

      burger.addEventListener('click', function() {
        burger.classList.toggle('is-active');
        nav.classList.toggle('is-active');
      });
    })();
    
//    $(document).ready(function() {
//     $('.menu-sub-list').click(function(){
//      $(this).toggleClass('tap');
//      });
//    });

//    $(document).ready(function(){
//      $('.menu-list li a').click(function(){
//        $('li a').removeClass("is-active");
//        $(this).addClass("is-active");
//      });
//    });

  </script>

</body>

</html>

<% else %>

<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cashless CMS</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <link rel="stylesheet" href="/assets/dasboard.css">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+HK:100,300,400,500,700,900&display=swap" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  
  <%= javascript_pack_tag "application" %>
  <%= csrf_meta_tags %>
  
  <style type="text/css">
    @import "compass/css3";

    * { box-sizing: border-box; margin: 0; padding:0; }
    
    body{
      display: block;
      height: auto;
      background: black;
      background-image: url("../images/bg-animo.png");
      background-size: cover; 
      background-repeat: no-repeat;
      background-position: 100% 100%;
      font-family: 'Helvetica Neue', Arial, Sans-Serif;
      overflow: hidden;
    }

    .wrp-login {
      
    }

    .login-wrap {
      height: 100vh;
      background: white;
      /*box-shadow: 3px 3px 10px #333;*/
      padding: 50px;
    }
   .txt-tagline{
      margin: 30px;
      padding: 50px;
      letter-spacing: 2px;
      color: white;
    }

    .txt-tagline h1{
        font-weight: 700;
        font-size: 50px;
      }

    h2 {
      text-align: center;
      font-weight: 200;
      font-size: 2em;
      margin-top: 10px;
      color: #34495e;
    }
     
   .button {
      background: #f6775e;
      border:none;
      color: white;
      font-size: 18px;
      font-weight: 700;
      cursor: pointer;
      transition: box-shadow .4s ease;
    }

    .button:hover {
      color: white;
      background-color: #f75f41;
      box-shadow: 1px 1px 5px #555;  
    }

    .button:active {
      box-shadow: 1px 1px 7px #222;  
    }
    .test{
      color: red;
    }

    @media only screen and (max-width: 768px){

    }

  </style>

</head>

<body> 
  <div class="wrp-login">
    <div class="columns">
      <section class="column">
        <div class="txt-tagline">
          <h1>Lorem Ipsum</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </section>
      <section class="column is-one-third"> 
        <div class="login-wrap">
          <%=yield%>
            <% if notice %>
              <p class="help is-success">
              <%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="help is-danger"><%= alert %></p>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</body>
<% end %>

app/views/layouts/navigations/_footer.html.erb
_footer.html.erb

app/views/layouts/navigations/_public.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="navbar is-black is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="#">           
          <!-- CRM -->
           <%#= image_tag(asset_path('animo.jpg')) %>
        </a>

        <a role="button" class="navbar-burger burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navMenu" class="navbar-menu">
        <div class="navbar-start">
          <a href="#" class="navbar-item">
            <%= link_to "Home", root_path, :class => 'navbar-item'%>
          </a>
          
          <a href="#" class="navbar-item">
            Documentation
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a href="#" class="navbar-item">
                About
              </a>
              <a href="#" class="navbar-item">
                Jobs
              </a>
              <a href="#" class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a href="#" class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= current_user.email%>
            </a>

            <div class="navbar-dropdown is-right">
              <!-- <a>
                <%#= link_to content_tag(:span , content_tag(:i , " " , class: "fas fa-user-circle" ), class:"icon" ) + content_tag(:span , " Edit Profile") , edit_registration_path,  method: :delete, :class => 'navbar-item' %>
              </a>
              <a>
                <%#= link_to content_tag(:span , content_tag(:i , " " , class: "far fa-envelope" ), class:"icon" ) + content_tag(:span , " Report") , destroy_user_session_path, method: :delete, :class => 'navbar-item' %>
              </a>
              <hr class="navbar-divider"> -->
              <a>
                <%= link_to content_tag(:span , content_tag(:i , " " , class: "fas fa-sign-out-alt" ), class:"icon" ) + content_tag(:span , " Logout") , destroy_user_session_path, method: :delete, :class => 'navbar-item' %>
              </a>
            </div> 
          </div>
<!--
          <div class="navbar-item">
            <%#= link_to content_tag(:span , content_tag(:i , " " , class: "fas fa-sign-out-alt" ), class:"icon" ) , destroy_user_session_path, method: :delete, title: " log Out" , :class => 'navbar-item' %>
          </div>
-->
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/navigations/_sidebar.html.erb
<aside id="sidebar-container">
  <div class="sidebar side-fixed menu " >
    <p class="menu-label">
      Menu
    </p>
    <ul class="menu-list">
      <li>
        <a class="is-active" href="/">
          <span class="icon">
            <i class="fas fa-tachometer-alt"></i>
          </span>
          <span class="menu-collapsed">Dashboard</span>
        </a>
      </li>

      <li class="menu-sub-list">
        
        <a href="#">
          <span class="icon">
            <i class="fa fa-tasks fa-fw"></i>
          </span> 
          <span class="menu-collapsed">Management</span>
        </a>

        <ul class="sidebar-submenu">
          <li class="menu-sub-sub-list">
            <%= link_to('#', root_path)%>
          </li>
        </ul>
      </li>

      <li class="menu-sub-list">
        <a href="#">
          <span class="icon">
            <i class="fas fa-users"></i>
          </span>
          <span class="menu-collapsed sub-plus">User</span>
          
        </a>

        <ul class="sidebar-submenu">
          <li>
            <%= link_to('lorem', root_path)%>
          </li>
          <li>
            <%= link_to('lorem', root_path)%>
          </li>
          <li>
            <%= link_to('lorem', root_path)%>
          </li>
        </ul>
      </li>

      <li class="menu-sub-list">
        <a href="#">
          <span class="icon">
            <i class="fas fa-dollar-sign"></i>
          </span>
          <span class="menu-collapsed">Transaction</span>
        </a>

        <ul class="sidebar-submenu">
          <li>
            <%= link_to('#', root_path)%>
          </li>
        </ul>
      </li>

      <div class="level">
      <li class="menu-sub-list">
        <a href="#">
          <span class="icon">
            <i class="fas fa-book"></i>
          </span>
          <span class="menu-collapsed">Report</span>
        </a>

        <ul class="sidebar-submenu">
          <li>
            <%= link_to('#', root_path)%>
          </li>
          <li>
            <%= link_to('#', root_path)%>
          </li>
        </ul>
      </li>
      </div>

    </ul>
  </div>
  
  <div class="menu sidebar-bottom">
    <ul class="menu-list">
      <li>
        <a href="#" data-toggle="sidebar-colapse" class="btn-collapse">
          <span id="collapse-icon" class="icon">
            <i class="fas fa-angle-double-left"></i>
          </span>
          <span class="menu-collapsed">Collapse</span>
        </a>
      </li>
    </ul> 
  </div>
</aside>

<script>
  $(document).ready(function(){
    $('.menu-sub-list').click(function(){
      $(this).toggleClass('tap');
    });
    
    $('[data-toggle=sidebar-colapse]').click(function () {
      SidebarCollapse();
    });
    
    function SidebarCollapse() {
      $('.menu-collapsed').toggleClass('menu-hidden');
      $('.sidebar-submenu').toggleClass('is-hidden');
      $('#sidebar-container').toggleClass(' sidebar-collapsed');
      $('#collapse-icon').toggleClass('<i class="fas fa-angle-double-right"></i>');
      $('#main').toggleClass('main-collapsed');
    }
    
    $('.menu-sub-list.a').filter(function(){
      return $(this).attr('href').toLowerCase() === window.location.pathname.toLowerCase();
    }).addClass('is-active');

//    $('.menu-sub-list a').filter(function(){
//      console.log($(this).attr('href').toLowerCase());
//      console.log($(this));
//      if($(this).attr('href').toLowerCase() == window.location.pathname.toLowerCase()){
//        $(this).addClass('is-active');
//      }else{
//        console.log($(this).attr('href').toLowerCase());
//        $(this).removeClass('is-active');
//      }
//    });
  });
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>